const transformImage = import('./getters/imageGetter');
const transformUser = import('./getters/userGetter');
const transformProject = import('./getters/projectGetter');
const transformPart = import('./getters/partGetter');
const transformBlock = import('./getters/BlockGetter');
const transformContent = import('./getters/contentGetter');
const transformDegree = import('./getters/degreeGetter');
const transformEmployment = import('./getters/employmentGetter');
const transformTraineeship = import('./getters/traineeshipGetter');

module.exports.transformImage = transformImage;
module.exports.transformUser = transformUser;
module.exports.transformProject = transformProject;
module.exports.transformPart = transformPart;
module.exports.transformBlock = transformBlock;
module.exports.transformContent = transformContent;
module.exports.transformDegree = transformDegree;
module.exports.transformEmployment = transformEmployment;
module.exports.transformTraineeship = transformTraineeship;